### ISSUE TITLE
Deprecated values

### ISSUE THREAD

**Issue by cybervoid** [valadas/get-release-branch-version#1]
Hi, 

I'm in need of something similar, I tested this action and noticed even though it's working the code has a lot of deprecations. Not sure if the repo is still alive, I'd be willing to update it so I don't have to create a similar action.
Let me know if that's something you are interested in.

![image](https://github.com/valadas/get-release-branch-version/assets/3310256/8e839a4b-aaed-43a2-aec4-62d8e413022d)

**Comment by valadas** [comment]
Sure thing, it's been working but I never really came back to update it (since it was working), PRs are welcome and I'll review/merge that quickly if one comes in to update this stuff... Thanks @cybervoid

**Comment by cybervoid** [comment]
That was quick!, I'll push the changes soon. I also wanted to check with you, if you are open to tweak that regex to also accept `release-x.xx.x`, not a deal breaker but that's the format my team is used to.

**Comment by valadas** [comment]
Yeah as long as the change is non breaking, if I remember, currently it woould support:
release/1.2.3
release/01.02.03
and so on, so yeah if the accepts `/` or `-` I am not opposed

**Comment by valadas** [comment]
Done in #2
